export const APP_ROUTES = {
  adoptionRequests: '/adoption-requests',
  achievements: '/achievements',
  achievementAssignment: '/achievements/assign',
  heroesWall: '/heroes-wall',
  calendar: '/calendar',
  companySettings: '/company-settings',
  communityListing: '/community-listing',
  dashboard: '/dashboard',
  donationLogs: '/donation-logs',
  donationList: '/donation-list',
  emergencySos: '/emergency-sos',
  eventList: '/events',
  login: '/login',
  paymentModeList: '/payment-mode-list',
  petList: '/pet-list',
  userList: '/user-list',
  veterinaryClinicList: '/veterinary-clinic-list',
  volunteerList: '/volunteer-list',
  root: '/',
} as const
